spring.datasource.url=jdbc:postgresql://localhost:5432/los_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

loan.processor.thread-count=5
loan.processor.processing-delay=25000
loan.agent-assignment.thread-count=5
loan.agent-assignment.processing-delay=1000